namespace CountryApp.Models
{
    public interface CountryBase
    {
        Name name { get; set; }
        Flags flags { get; set; }
        string[] tld { get; set; }
        CurrenciesStr currencies { get; set; }
        Languages languages { get; set; }
        int population { get; set; }
        string[] capital { get; set; }
        string _currencies { get; set; }
        string _languages { get; set; }
        string _tld { get; set; }
    }

    public interface Region
    {
        string name { get; set; }
        string code { get; set; }
    }

    public interface Flags
    {
        string png { get; set; }
        string svg { get; set; }
        string alt { get; set; }
    }

    public interface Languages
    {
        string spa { get; set; }
        string zho { get; set; }
        string eng { get; set; }
        string msa { get; set; }
        string tam { get; set; }
        string bos { get; set; }
        string hrv { get; set; }
        string srp { get; set; }
        string div { get; set; }
        string lav { get; set; }
        string ell { get; set; }
        string fra { get; set; }
        string ara { get; set; }
        string ben { get; set; }
        string smo { get; set; }
        string ita { get; set; }
        string dzo { get; set; }
        string por { get; set; }
        string nau { get; set; }
        string nno { get; set; }
        string nob { get; set; }
        string smi { get; set; }
        string tvl { get; set; }
        string hin { get; set; }
        string khm { get; set; }
        string mfe { get; set; }
        string kon { get; set; }
        string lin { get; set; }
        string lua { get; set; }
        string swa { get; set; }
        string nld { get; set; }
        string heb { get; set; }
        string ber { get; set; }
        string mey { get; set; }
        string kin { get; set; }
        string tur { get; set; }
        string mah { get; set; }
        string rus { get; set; }
        string nrf { get; set; }
        string rar { get; set; }
        string niu { get; set; }
        string slv { get; set; }
        string hmo { get; set; }
        string tpi { get; set; }
        string mya { get; set; }
        string pap { get; set; }
        string fil { get; set; }
        string kaz { get; set; }
        string sqi { get; set; }
        string grn { get; set; }
        string tgk { get; set; }
        string aze { get; set; }
        string ron { get; set; }
        string bul { get; set; }
        string mkd { get; set; }
        string prs { get; set; }
        string pus { get; set; }
        string tuk { get; set; }
        string tsn { get; set; }
        string som { get; set; }
        string swe { get; set; }
        string deu { get; set; }
        string mlg { get; set; }
        string ukr { get; set; }
        string fas { get; set; }
        string pol { get; set; }
        string bis { get; set; }
        string pau { get; set; }
        string aym { get; set; }
        string que { get; set; }
        string ssw { get; set; }
        string ltz { get; set; }
        string hat { get; set; }
        string isl { get; set; }
        string fij { get; set; }
        string hif { get; set; }
        string kor { get; set; }
        string lit { get; set; }
        string kat { get; set; }
        string sag { get; set; }
        string mon { get; set; }
        string kal { get; set; }
        string amh { get; set; }
        string afr { get; set; }
        string her { get; set; }
        string hgm { get; set; }
        string kwn { get; set; }
        string loz { get; set; }
        string ndo { get; set; }
        string ind { get; set; }
        string bel { get; set; }
        string nor { get; set; }
        string mlt { get; set; }
        string nbl { get; set; }
        string nso { get; set; }
        string sot { get; set; }
        string tso { get; set; }
        string ven { get; set; }
        string xho { get; set; }
        string zul { get; set; }
        string hye { get; set; }
        string cat { get; set; }
        string nfr { get; set; }
        string ces { get; set; }
        string slk { get; set; }
        string urd { get; set; }
        string lat { get; set; }
        string jam { get; set; }
        string zdj { get; set; }
        string tir { get; set; }
        string bwg { get; set; }
        string kck { get; set; }
        string khi { get; set; }
        string ndc { get; set; }
        string nde { get; set; }
        string nya { get; set; }
        string sna { get; set; }
        string toi { get; set; }
        string zib { get; set; }
        string est { get; set; }
        string bjz { get; set; }
        string mri { get; set; }
        string nzs { get; set; }
        string bar { get; set; }
        string nep { get; set; }
        string dan { get; set; }
        string fao { get; set; }
        string tkl { get; set; }
        string glv { get; set; }
        string kir { get; set; }
        string cal { get; set; }
        string cha { get; set; }
        string tet { get; set; }
        string vie { get; set; }
        string gle { get; set; }
        string fin { get; set; }
        string jpn { get; set; }
        string pih { get; set; }
        string cnr { get; set; }
        string lao { get; set; }
        string hun { get; set; }
        string ton { get; set; }
        string arc { get; set; }
        string ckb { get; set; }
        string tha { get; set; }
        string run { get; set; }
        string gsw { get; set; }
        string roh { get; set; }
        string gil { get; set; }
        string uzb { get; set; }
        string sin { get; set; }
        string pov { get; set; }
        string crs { get; set; }
    }

    public interface Currencies
    {
        CurrenciesStr GTQ { get; set; }
        CurrenciesStr SGD { get; set; }
        CurrenciesStr BAM { get; set; }
        CurrenciesStr MVR { get; set; }
        CurrenciesStr EUR { get; set; }
        CurrenciesStr AUD { get; set; }
        CurrenciesStr JOD { get; set; }
        CurrenciesStr BDT { get; set; }
        CurrenciesStr USD { get; set; }
        CurrenciesStr DZD { get; set; }
        CurrenciesStr BTN { get; set; }
        CurrenciesStr INR { get; set; }
        CurrenciesStr STN { get; set; }
        CurrenciesStr XAF { get; set; }
        CurrenciesStr XPF { get; set; }
        CurrenciesStr NOK { get; set; }
        CurrenciesStr TVD { get; set; }
        CurrenciesStr KHR { get; set; }
        CurrenciesStr MUR { get; set; }
        CurrenciesStr CDF { get; set; }
        CurrenciesStr PAB { get; set; }
        CurrenciesStr NIO { get; set; }
        CurrenciesStr SLL { get; set; }
        CurrenciesStr BBD { get; set; }
        CurrenciesStr ILS { get; set; }
        CurrenciesStr MAD { get; set; }
        CurrenciesStr MRU { get; set; }
        CurrenciesStr XCD { get; set; }
        CurrenciesStr RWF { get; set; }
        CurrenciesStr TRY { get; set; }
        CurrenciesStr MZN { get; set; }
        CurrenciesStr NGN { get; set; }
        CurrenciesStr RUB { get; set; }
        CurrenciesStr CUC { get; set; }
        CurrenciesStr CUP { get; set; }
        CurrenciesStr GBP { get; set; }
        CurrenciesStr JEP { get; set; }
        CurrenciesStr CRC { get; set; }
        CurrenciesStr CKD { get; set; }
        CurrenciesStr NZD { get; set; }
        CurrenciesStr PGK { get; set; }
        CurrenciesStr HNL { get; set; }
        CurrenciesStr MOP { get; set; }
        CurrenciesStr TTD { get; set; }
        CurrenciesStr GMD { get; set; }
        CurrenciesStr MMK { get; set; }
        CurrenciesStr EGP { get; set; }
        CurrenciesStr LBP { get; set; }
        CurrenciesStr KES { get; set; }
        CurrenciesStr PHP { get; set; }
        CurrenciesStr KZT { get; set; }
        CurrenciesStr ARS { get; set; }
        CurrenciesStr TJS { get; set; }
        CurrenciesStr AZN { get; set; }
        CurrenciesStr RON { get; set; }
        CurrenciesStr CLP { get; set; }
        CurrenciesStr CVE { get; set; }
        CurrenciesStr BGN { get; set; }
        CurrenciesStr UYU { get; set; }
        CurrenciesStr MKD { get; set; }
        CurrenciesStr AFN { get; set; }
        CurrenciesStr BWP { get; set; }
        CurrenciesStr CAD { get; set; }
        CurrenciesStr QAR { get; set; }
        CurrenciesStr YER { get; set; }
        CurrenciesStr SOS { get; set; }
        CurrenciesStr SEK { get; set; }
        CurrenciesStr CHF { get; set; }
        CurrenciesStr SHP { get; set; }
        CurrenciesStr MGA { get; set; }
        CurrenciesStr UAH { get; set; }
        CurrenciesStr IRR { get; set; }
        CurrenciesStr PLN { get; set; }
        CurrenciesStr VUV { get; set; }
        CurrenciesStr PEN { get; set; }
        CurrenciesStr SZL { get; set; }
        CurrenciesStr ZAR { get; set; }
        CurrenciesStr DJF { get; set; }
        CurrenciesStr HTG { get; set; }
        CurrenciesStr SYP { get; set; }
        CurrenciesStr GIP { get; set; }
        CurrenciesStr MXN { get; set; }
        CurrenciesStr ISK { get; set; }
        CurrenciesStr FJD { get; set; }
        CurrenciesStr KPW { get; set; }
        CurrenciesStr SBD { get; set; }
        CurrenciesStr GNF { get; set; }
        CurrenciesStr BHD { get; set; }
        CurrenciesStr GEL { get; set; }
        CurrenciesStr RSD { get; set; }
        CurrenciesStr XOF { get; set; }
        CurrenciesStr MNT { get; set; }
        CurrenciesStr DKK { get; set; }
        CurrenciesStr ETB { get; set; }
        CurrenciesStr LYD { get; set; }
        CurrenciesStr NAD { get; set; }
        CurrenciesStr MDL { get; set; }
        CurrenciesStr BOB { get; set; }
        CurrenciesStr DOP { get; set; }
        CurrenciesStr ANG { get; set; }
        CurrenciesStr IDR { get; set; }
        CurrenciesStr BYN { get; set; }
        CurrenciesStr LRD { get; set; }
        CurrenciesStr AMD { get; set; }
        CurrenciesStr ALL { get; set; }
        CurrenciesStr SSP { get; set; }
        CurrenciesStr GGP { get; set; }
        CurrenciesStr AED { get; set; }
        CurrenciesStr CZK { get; set; }
        CurrenciesStr PKR { get; set; }
        CurrenciesStr JMD { get; set; }
        CurrenciesStr KMF { get; set; }
        CurrenciesStr FKP { get; set; }
        CurrenciesStr TMT { get; set; }
        CurrenciesStr BND { get; set; }
        CurrenciesStr GHS { get; set; }
        CurrenciesStr KWD { get; set; }
        CurrenciesStr ERN { get; set; }
        CurrenciesStr ZWL { get; set; }
        CurrenciesStr TZS { get; set; }
        CurrenciesStr BZD { get; set; }
        CurrenciesStr SAR { get; set; }
        CurrenciesStr COP { get; set; }
        CurrenciesStr MYR { get; set; }
        CurrenciesStr BMD { get; set; }
        CurrenciesStr WST { get; set; }
        CurrenciesStr UGX { get; set; }
        CurrenciesStr NPR { get; set; }
        CurrenciesStr PYG { get; set; }
        CurrenciesStr FOK { get; set; }
        CurrenciesStr ZMW { get; set; }
        CurrenciesStr IMP { get; set; }
        CurrenciesStr KGS { get; set; }
        CurrenciesStr HKD { get; set; }
        CurrenciesStr VND { get; set; }
        CurrenciesStr JPY { get; set; }
        CurrenciesStr BRL { get; set; }
        CurrenciesStr GYD { get; set; }
        CurrenciesStr CNY { get; set; }
        CurrenciesStr AWG { get; set; }
        CurrenciesStr LAK { get; set; }
        CurrenciesStr VES { get; set; }
        CurrenciesStr HUF { get; set; }
        CurrenciesStr TOP { get; set; }
        CurrenciesStr IQD { get; set; }
        CurrenciesStr THB { get; set; }
        CurrenciesStr TND { get; set; }
        CurrenciesStr BIF { get; set; }
        CurrenciesStr KID { get; set; }
        CurrenciesStr SDG { get; set; }
        CurrenciesStr UZS { get; set; }
        CurrenciesStr LKR { get; set; }
        CurrenciesStr SRD { get; set; }
        CurrenciesStr AOA { get; set; }
        CurrenciesStr KYD { get; set; }
        CurrenciesStr LSL { get; set; }
        CurrenciesStr MWK { get; set; }
        CurrenciesStr BSD { get; set; }
        CurrenciesStr SCR { get; set; }
        CurrenciesStr TWD { get; set; }
        CurrenciesStr KRW { get; set; }
        CurrenciesStr OMR { get; set; }
    }

    public interface CurrenciesStr
    {
        string name { get; set; }
        string symbol { get; set; }
    }

    public interface Name
    {
        string common { get; set; }
        string official { get; set; }
        NativeName nativeName { get; set; }
    }

    public interface NativeName
    {
        NativeNameStr spa { get; set; }
        NativeNameStr zho { get; set; }
        NativeNameStr eng { get; set; }
        NativeNameStr msa { get; set; }
        NativeNameStr tam { get; set; }
        NativeNameStr bos { get; set; }
        NativeNameStr hrv { get; set; }
        NativeNameStr srp { get; set; }
        NativeNameStr div { get; set; }
        NativeNameStr lav { get; set; }
        NativeNameStr ell { get; set; }
        NativeNameStr fra { get; set; }
        NativeNameStr ara { get; set; }
        NativeNameStr ben { get; set; }
        NativeNameStr smo { get; set; }
        NativeNameStr ita { get; set; }
        NativeNameStr dzo { get; set; }
        NativeNameStr por { get; set; }
        NativeNameStr nau { get; set; }
        NativeNameStr nno { get; set; }
        NativeNameStr nob { get; set; }
        NativeNameStr smi { get; set; }
        NativeNameStr tvl { get; set; }
        NativeNameStr hin { get; set; }
        NativeNameStr khm { get; set; }
        NativeNameStr mfe { get; set; }
        NativeNameStr kon { get; set; }
        NativeNameStr lin { get; set; }
        NativeNameStr lua { get; set; }
        NativeNameStr swa { get; set; }
        NativeNameStr nld { get; set; }
        NativeNameStr heb { get; set; }
        NativeNameStr ber { get; set; }
        NativeNameStr mey { get; set; }
        NativeNameStr kin { get; set; }
        NativeNameStr tur { get; set; }
        NativeNameStr mah { get; set; }
        NativeNameStr rus { get; set; }
        NativeNameStr nrf { get; set; }
        NativeNameStr rar { get; set; }
        NativeNameStr niu { get; set; }
        NativeNameStr slv { get; set; }
        NativeNameStr hmo { get; set; }
        NativeNameStr tpi { get; set; }
        NativeNameStr mya { get; set; }
        NativeNameStr pap { get; set; }
        NativeNameStr fil { get; set; }
        NativeNameStr kaz { get; set; }
        NativeNameStr sqi { get; set; }
        NativeNameStr grn { get; set; }
        NativeNameStr tgk { get; set; }
        NativeNameStr aze { get; set; }
        NativeNameStr ron { get; set; }
        NativeNameStr bul { get; set; }
        NativeNameStr mkd { get; set; }
        NativeNameStr prs { get; set; }
        NativeNameStr pus { get; set; }
        NativeNameStr tuk { get; set; }
        NativeNameStr tsn { get; set; }
        NativeNameStr som { get; set; }
        NativeNameStr swe { get; set; }
        NativeNameStr deu { get; set; }
        NativeNameStr mlg { get; set; }
        NativeNameStr ukr { get; set; }
        NativeNameStr fas { get; set; }
        NativeNameStr pol { get; set; }
        NativeNameStr bis { get; set; }
        NativeNameStr pau { get; set; }
        NativeNameStr aym { get; set; }
        NativeNameStr que { get; set; }
        NativeNameStr ssw { get; set; }
        NativeNameStr ltz { get; set; }
        NativeNameStr hat { get; set; }
        NativeNameStr isl { get; set; }
        NativeNameStr fij { get; set; }
        NativeNameStr hif { get; set; }
        NativeNameStr kor { get; set; }
        NativeNameStr lit { get; set; }
        NativeNameStr kat { get; set; }
        NativeNameStr sag { get; set; }
        NativeNameStr mon { get; set; }
        NativeNameStr kal { get; set; }
        NativeNameStr amh { get; set; }
        NativeNameStr afr { get; set; }
        NativeNameStr her { get; set; }
        NativeNameStr hgm { get; set; }
        NativeNameStr kwn { get; set; }
        NativeNameStr loz { get; set; }
        NativeNameStr ndo { get; set; }
        NativeNameStr ind { get; set; }
        NativeNameStr bel { get; set; }
        NativeNameStr nor { get; set; }
        NativeNameStr mlt { get; set; }
        NativeNameStr nbl { get; set; }
        NativeNameStr nso { get; set; }
        NativeNameStr sot { get; set; }
        NativeNameStr tso { get; set; }
        NativeNameStr ven { get; set; }
        NativeNameStr xho { get; set; }
        NativeNameStr zul { get; set; }
        NativeNameStr hye { get; set; }
        NativeNameStr cat { get; set; }
        NativeNameStr nfr { get; set; }
        NativeNameStr ces { get; set; }
        NativeNameStr slk { get; set; }
        NativeNameStr urd { get; set; }
        NativeNameStr lat { get; set; }
        NativeNameStr jam { get; set; }
        NativeNameStr zdj { get; set; }
        NativeNameStr tir { get; set; }
        NativeNameStr bwg { get; set; }
        NativeNameStr kck { get; set; }
        NativeNameStr khi { get; set; }
        NativeNameStr ndc { get; set; }
        NativeNameStr nde { get; set; }
        NativeNameStr nya { get; set; }
        NativeNameStr sna { get; set; }
        NativeNameStr toi { get; set; }
        NativeNameStr zib { get; set; }
        NativeNameStr est { get; set; }
        NativeNameStr bjz { get; set; }
        NativeNameStr mri { get; set; }
        NativeNameStr nzs { get; set; }
        NativeNameStr bar { get; set; }
        NativeNameStr nep { get; set; }
        NativeNameStr dan { get; set; }
        NativeNameStr fao { get; set; }
        NativeNameStr tkl { get; set; }
        NativeNameStr glv { get; set; }
        NativeNameStr kir { get; set; }
        NativeNameStr cal { get; set; }
        NativeNameStr cha { get; set; }
        NativeNameStr tet { get; set; }
        NativeNameStr vie { get; set; }
        NativeNameStr gle { get; set; }
        NativeNameStr fin { get; set; }
        NativeNameStr jpn { get; set; }
        NativeNameStr pih { get; set; }
        NativeNameStr cnr { get; set; }
        NativeNameStr lao { get; set; }
        NativeNameStr hun { get; set; }
        NativeNameStr ton { get; set; }
        NativeNameStr arc { get; set; }
        NativeNameStr ckb { get; set; }
        NativeNameStr tha { get; set; }
        NativeNameStr run { get; set; }
        NativeNameStr gsw { get; set; }
        NativeNameStr roh { get; set; }
        NativeNameStr gil { get; set; }
        NativeNameStr uzb { get; set; }
        NativeNameStr sin { get; set; }
        NativeNameStr pov { get; set; }
        NativeNameStr crs { get; set; }
    }

    public interface NativeNameStr
    {
        string common { get; set; }
        string official { get; set; }
    }
}
